###############################
# etcd
# https://github.com/etcd-io/etcd/releases
###############################

# Download etcd
- name: Download etcd
  copy:
    src: "etcd-v{{ etcd_version }}-linux-{{ host_arch }}.tar.gz"
    dest: /tmp/etcd.tar.gz 

#Decompress nodejs
- name: Decompress nodejs
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: "/tmp/"
    remote_src: yes

# Move etcd files to /usr/local/bin/
- name: Move etcd files to /usr/local/bin/
  shell: mv /tmp/etcd-v{{ etcd_version }}-linux-{{ host_arch }}/etcd* /usr/local/bin/

# Template for etcd.service
- name: Template for etcd.service
  template:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service

# Enable and start etcd.service
- name: Enable and start etcd.service
  shell: |
    systemctl daemon-reload
    systemctl enable etcd.service
    systemctl stop etcd.service

###############################
# kubelet
# https://kubernetes.io/releases/download/
###############################

# Download kubelet
- name: Download kubelet
  copy:
    src: kubelet_v{{ k8s_version }}
    dest: /tmp/kubelet

# Install kubelet
- name: Install kubelet
  command: install -m 755 /tmp/kubelet /usr/local/bin/

# Template for kubelet-config.yaml
- name: Template for kubelet-config.yaml
  template:
    src: kubelet-config.yaml
    dest: /etc/kubernetes/config/kubelet-config.yaml

# Configure SUBNET
- name: Configure SUBNET
  shell: |
    sed "s|SUBNET|{{ subnet }}|g" /etc/kubernetes/config/kubelet-config.yaml > /etc/kubernetes/config/kubelet-config.yaml.tmp
    mv /etc/kubernetes/config/kubelet-config.yaml.tmp /etc/kubernetes/config/kubelet-config.yaml.conf

# Template for kubelet.service
- name: Template for kubelet.service
  template:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service

# Enable and start kubelet.service
- name: Enable and start kubelet.service
  shell: |
    systemctl daemon-reload
    systemctl enable kubelet.service
    systemctl stop kubelet.service

###############################
# kubectl
# https://kubernetes.io/releases/download/
###############################

# Download kubectl
- name: Download kubectl
  copy:
    src: kubectl_v{{ k8s_version }}
    dest: /tmp/kubectl

# Install kubelet
- name: Install kubectl
  command: install -m 755 /tmp/kubectl /usr/local/bin/


###############################
#
#
###############################
# Remove /tmp/kubelet
- name: Remove /tmp/kubelet
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "/tmp/etcd.tar.gz "
    - "/tmp/kubectl"
    - "/tmp/kubelet"


# sudo journalctl -u kubelet.service -f
# sudo journalctl -u etcd.service -f

# systemctl status kubelet.service
# systemctl status etcd.service
