###############################
# etcd
# https://github.com/etcd-io/etcd/releases
###############################

# Download etcd
- name: Download etcd
  copy:
    src: "etcd-v{{ etcd_version }}-linux-{{ host_arch }}.tar.gz"
    dest: /tmp/etcd.tar.gz 
  when: etcd_version is defined

#Decompress nodejs
- name: Decompress nodejs
  unarchive:
    src: /tmp/etcd.tar.gz
    dest: "/tmp/"
    remote_src: yes
  when: etcd_version is defined

# Move etcd files to /usr/local/bin/
- name: Move etcd files to /usr/local/bin/
  shell: mv /tmp/etcd-v{{ etcd_version }}-linux-{{ host_arch }}/etcd* /usr/local/bin/
  when: etcd_version is defined

# Template for etcd.service
- name: Template for etcd.service
  template:
    src: etcd.service
    dest: /etc/systemd/system/etcd.service
  when: etcd_version is defined

# Enable and start etcd.service
- name: Enable and start etcd.service
  shell: |
    systemctl daemon-reload
    systemctl enable etcd.service
    systemctl stop etcd.service
  when: etcd_version is defined

###############################
# kubelet
# https://kubernetes.io/releases/download/
###############################

# Download kubelet
- name: Download kubelet
  copy:
    src: kubelet_v{{ k8s_version }}
    dest: /tmp/kubelet

# Install kubelet
- name: Install kubelet
  command: install -m 755 /tmp/kubelet /usr/local/bin/

# Template for kubelet-config.yaml
- name: Template for kubelet-config.yaml
  template:
    src: kubelet-config.yaml
    dest: /etc/kubernetes/config/kubelet-config.yaml

# Template for kubelet.service
- name: Template for kubelet.service
  template:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service

# Enable and start kubelet.service
- name: Enable and start kubelet.service
  shell: |
    systemctl daemon-reload
    systemctl enable kubelet.service
    systemctl stop kubelet.service


###############################
# kube-proxy
# https://kubernetes.io/releases/download/
###############################

# Download kube-proxy
- name: Download kube-proxy
  copy:
    src: kube-proxy_v{{ k8s_version }}
    dest: /tmp/kube-proxy 

# Install kube-proxy
- name: Install kube-proxy
  command: install -m 755 /tmp/kube-proxy /usr/local/bin/

# Template for kube-proxy.service
- name: Template for kube-proxy.service
  template:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service

# Template for kube-proxy-config.yaml
- name: Template for kube-proxy-config.yaml
  template:
    src: kube-proxy-config.yaml
    dest: /etc/kubernetes/config/kube-proxy-config.yaml

# Enable and start kube-proxy.service
- name: Enable and start kube-proxy.service
  shell: |
    systemctl daemon-reload
    systemctl enable kube-proxy.service
    systemctl stop kube-proxy.service

###############################
# kubectl
# https://kubernetes.io/releases/download/
###############################

# Download kubectl
- name: Download kubectl
  copy:
    src: kubectl_v{{ k8s_version }}
    dest: /tmp/kubectl

# Install kubelet
- name: Install kubectl
  command: install -m 755 /tmp/kubectl /usr/local/bin/

###############################
#
#
###############################
# Remove /tmp/kubelet
- name: Remove /tmp/kubelet
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "/tmp/etcd.tar.gz"
    - "/tmp/kubectl"
    - "/tmp/kubelet"


