all:
  children:

    k8scontrol1:
      hosts:
        k8scontrol1:  
          host_ip: 192.168.129.214
          host_type: control_plane 
          host_arch: arm64 
          runc_version: 1.2.0  
          containerd_version: 2.0.0  
          cni_plugins_version: 1.6.0
          crictl_version: 1.31.1
          k8s_version: 1.31.2
          etcd_version: 3.5.16
          subnet: 10.200.1.0/24

    k8snode1:
      hosts:
        k8snode1:
          host_ip: 192.168.129.215
          host_type: node
          host_arch: arm64  
          runc_version: 1.2.0  
          containerd_version: 2.0.0   
          cni_plugins_version: 1.6.0
          crictl_version: 1.31.1
          k8s_version: 1.31.2
          etcd_version: 3.5.16
          subnet: 10.200.2.0/24
        
  vars:
    host_timezone: Europe/Brussels
    clusterDNS: 10.32.0.10
    root_user: joao



