all:
  children:

    k8scontrol1:
      hosts:
        k8scontrol1:  
          host_ip: 192.168.129.224
          host_type: control_plane_master
          host_arch: arm64 
          runc_version: 1.2.0  
          containerd_version: 2.0.0  
          cni_plugins_version: 1.6.0
          crictl_version: 1.31.1
          k8s_version: 1.31.2
          etcd_version: 3.5.16
          coredns_version: 1.11.3
          subnet: 10.200.1.0/24

#    k8scontrol2:
#      hosts:
#        k8scontrol2:  
#          host_ip: 192.168.129.221
#          host_type: control_plane 
#          host_arch: arm64 
#          runc_version: 1.2.0  
#          containerd_version: 2.0.0  
#          cni_plugins_version: 1.6.0
#          crictl_version: 1.31.1
#          k8s_version: 1.31.2
#          #etcd_version: 3.5.16
#          coredns_version: 1.11.3
#          subnet: 10.200.2.0/24

    k8snode1:
      hosts:
        k8snode1:
          host_ip: 192.168.129.225
          host_type: node
          host_arch: arm64  
          runc_version: 1.2.0  
          containerd_version: 2.0.0   
          cni_plugins_version: 1.6.0
          crictl_version: 1.31.1
          k8s_version: 1.31.2
          #etcd_version: 3.5.16
          subnet: 10.200.3.0/24

    k8snode2:
      hosts:
        k8snode2:
          host_ip: 192.168.129.226
          host_type: node
          host_arch: arm64  
          runc_version: 1.2.0  
          containerd_version: 2.0.0   
          cni_plugins_version: 1.6.0
          crictl_version: 1.31.1
          k8s_version: 1.31.2
          #etcd_version: 3.5.16
          subnet: 10.200.4.0/24
        
  vars:
    host_timezone: Europe/Brussels
    serverCIDR: 192.168.129.0/24
    clusterCIDR: 10.200.0.0/16
    clusterDNS: 10.33.0.10
    service_cluster_ip_range: 10.33.0.0/24
    api_address: 10.33.0.1
    root_user: joao



