- name: Default playbook - Starting Deploy
  hosts: k8scontrol1, k8snode1, k8snode2
  become: true
  roles:
    #- prepare_env
    #- container_runtime    
    #- prepare_kubelet_etcd
    #- prepare_control_plane
    #- certificates
    #- coreDNS
    - restart
    #- remove

