apiVersion: v1
kind: Service
metadata:
  name: nodered-service
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  selector:
    app: nodered
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1880
      targetPort: 1880
      nodePort: 30001