# Build container image  
FROM centos:8

LABEL org.opencontainers.image.authors="Joao Kauling Neto" \
      org.opencontainers.image.documentation="Container image for Ansible 2.13.13"

COPY files/* /tmp

# Combina todos os comandos em uma única instrução RUN
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    dnf -y --nodocs update && \
    dnf -y --nodocs install wget passwd openssh-server openssh-clients sudo python38 python38-pip && \
    dnf -y --nodocs install https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/sshpass-1.09-4.el8.x86_64.rpm && \
    useradd ansible && \
    echo "ansible:ansible" | chpasswd && \
    usermod -aG wheel ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    # Executa comandos para instalar Ansible no usuário ansible
    su - ansible -c "python3 -m pip install --upgrade pip setuptools --user" && \
    su - ansible -c "python3 -m pip install ansible==6.7.0 --user" && \
    su - ansible -c "mkdir /home/ansible/inventory /home/ansible/log /home/ansible/playbook /home/ansible/roles /home/ansible/scripts" && \
    mv /tmp/ansible_init_setup.sh /home/ansible/scripts/ansible_init_setup.sh && \
    mv /tmp/ansible_profile.sh /etc/profile.d/ansible_profile.sh && \
    mv /tmp/ansible.cfg /home/ansible/.ansible.cfg && \
    chown ansible:ansible /home/ansible/scripts/ansible_init_setup.sh && \
    chmod 755 /home/ansible/scripts/ansible_init_setup.sh && \
    sed -i 's/\r$//' /home/ansible/scripts/ansible_init_setup.sh && \
    echo "127.0.0.1        localhost" > /home/ansible/scripts/hosts_files && \
    dnf clean all && rm -rf /var/cache/dnf /tmp/*    

CMD ["/usr/sbin/init"]

# Comando para criar o container
#docker run -dit --name ansible ansible:2.13.13 /usr/sbin/init

#docker run -dit --name ansible \
#  -v C:/docker/ansible/inventory:/home/ansible/inventory \
#  -v C:/docker/ansible/log:/home/ansible/log \
#  -v C:/docker/ansible/playbook:/home/ansible/playbook \
#  -v C:/docker/ansible/roles:/home/ansible/roles \
#  ansible:2.13.13 /usr/sbin/init

#docker exec -it ansible bash
